services:
  control-node:
    build:
      context: .
      dockerfile: ControlNode.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ValidationNodes__Urls__0: http://validation-node-1:8080
      ValidationNodes__Urls__1: http://validation-node-2:8080
      ValidationNodes__Urls__2: http://validation-node-3:8080
    depends_on:
      - validation-node-1
      - validation-node-2
      - validation-node-3

  validation-node-1:
    build:
      context: .
      dockerfile: ValidationNode.Api/Dockerfile
    environment:
      NodeId: validation-node-1

  validation-node-2:
    build:
      context: .
      dockerfile: ValidationNode.Api/Dockerfile
    environment:
      NodeId: validation-node-2

  validation-node-3:
    build:
      context: .
      dockerfile: ValidationNode.Api/Dockerfile
    environment:
      NodeId: validation-node-3