using Json.Schema;

namespace ElectricTruckJsonValidator;

/// <summary>
/// Evaluates a JSON instance file against a JSON schema file.
/// </summary>
public interface IJsonSchemaValidator
{
	/// <summary>
	/// Executes schema validation using the configured validation engine.
	/// </summary>
	/// <param name="jsonFilePath">Path to the JSON instance file.</param>
	/// <param name="schemaFilePath">Path to the JSON schema file.</param>
	/// <returns>The evaluation results generated by the schema engine.</returns>
	Task<EvaluationResults> ValidateAsync(string jsonFilePath, string schemaFilePath);
}