using Json.Schema;
using System.Text.Json;

namespace ElectricTruckJsonValidator;

/// <summary>
/// Loads JSON and JSON schema text, then evaluates the document against the schema.
/// </summary>
public sealed class JsonSchemaValidator : IJsonSchemaValidator
{
	/// <summary>
	/// Executes schema validation using JsonSchema.Net list output for detailed errors.
	/// </summary>
	/// <param name="jsonFilePath">Path to the JSON instance file.</param>
	/// <param name="schemaFilePath">Path to the JSON schema file.</param>
	/// <returns>The evaluation results generated by the schema engine.</returns>
	public async Task<EvaluationResults> ValidateAsync(string jsonFilePath, string schemaFilePath)
	{
		var jsonText = await File.ReadAllTextAsync(jsonFilePath);
		var schemaText = await File.ReadAllTextAsync(schemaFilePath);

		using var jsonDocument = JsonDocument.Parse(jsonText);

		// Clone the root so the instance survives after JsonDocument disposal.
		var instance = jsonDocument.RootElement.Clone();
		var schema = JsonSchema.FromText(schemaText);
		var options = new EvaluationOptions
		{
			OutputFormat = OutputFormat.List
		};

		return schema.Evaluate(instance, options);
	}
}
