using Json.Schema;
using System.Text.Json;

namespace ElectricTruckJsonValidator;

/// <summary>
/// Loads JSON and JSON schema text, then evaluates the document against the schema.
/// </summary>
public sealed class JsonSchemaValidator
{
	/// <summary>
	/// Loads and parses a JSON schema from file for reuse across multiple validations.
	/// </summary>
	/// <param name="schemaFilePath">Path to the JSON schema file.</param>
	/// <returns>The parsed schema object.</returns>
	public async Task<JsonSchema> LoadSchemaAsync(string schemaFilePath)
	{
		var schemaText = await File.ReadAllTextAsync(schemaFilePath);
		return JsonSchema.FromText(schemaText);
	}

	/// <summary>
	/// Executes schema validation using JsonSchema.Net list output for detailed errors.
	/// </summary>
	/// <param name="jsonFilePath">Path to the JSON instance file.</param>
	/// <param name="schemaFilePath">Path to the JSON schema file.</param>
	/// <returns>The evaluation results generated by the schema engine.</returns>
	public async Task<EvaluationResults> ValidateAsync(string jsonFilePath, string schemaFilePath)
	{
		var schema = await LoadSchemaAsync(schemaFilePath);
		return await ValidateAsync(jsonFilePath, schema);
	}

	/// <summary>
	/// Executes schema validation against a pre-loaded schema.
	/// </summary>
	/// <param name="jsonFilePath">Path to the JSON instance file.</param>
	/// <param name="schema">The pre-loaded JSON schema.</param>
	/// <returns>The evaluation results generated by the schema engine.</returns>
	public async Task<EvaluationResults> ValidateAsync(string jsonFilePath, JsonSchema schema)
	{
		var jsonText = await File.ReadAllTextAsync(jsonFilePath);

		using var jsonDocument = JsonDocument.Parse(jsonText);

		// Clone the root so the instance survives after JsonDocument disposal.
		var instance = jsonDocument.RootElement.Clone();
		var options = new EvaluationOptions
		{
			OutputFormat = OutputFormat.List
		};
		return schema.Evaluate(instance, options);
	}
}
